services:
  frontend: 
    build: frontend
    container_name: school_manager_front
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    command: run dev 
    tty: true
    environment:
      - VITE_BACK_URL=localhost:3333
  backend:
    build: backend
    container_name: school_manager_back
    ports:
      - 3333:3333
    environment:
      SECRET_TOKEN: algumacoisa.com
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_NAME: school_manager
      MYSQL_HOST: db
      NODE_ENV: development
      MYSQL_PORT: 3306
    volumes:
      - ./backend/src:/app/src
    command: run dev 
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    container_name: school_manager_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_manager
    ports:
      - 3306:3306